### ISSUE TITLE
Fix undefined behaviour error message coming from background tasks

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-polykey#797]
### Specification

When starting an existing agent that hasn't run for a little while we get the following warning logger message.

![image](https://github.com/user-attachments/assets/098e7c09-8e60-486f-966e-b717c36b8511)

We'll need to find the cause for this and fix it. There aren't many tasks that persist between restarts so it should be simple to narrow down. But in that vein we need to make the following changes to make these problems more clear.

1. The message should mention which task handler failed.
2. Any usage of `utils.never()` should include a descriptive message of what shouldn't be happening. so we need to update all usage of never in a task handler.

### Tasks

1. Update the warning log for a failed task handler to include more information about what task was running.
2. Update the `utils.never()` usages in task handlers to include proper failure descriptions.
3. Find and determine the failure occurring here and fix it.

**Comment by tegefaulkes** [comment]
After updating the error stringification recently we've found that this is due to a failure to parse the GestaltId for a task when discovering.

**Comment by tegefaulkes** [comment]
@aryanjassal You're taking this over next as part of looking into the recent bugs.

**Comment by aryanjassal** [comment]
After some investigation, I believe that the error is happening somewhere from the `start()` method. In the `start` method, we first register the handler for `checkRediscoveryHandler`, then we schedule a task with that. However, we don't give it any parameters.

Note that to get the error reliably, I changed the `rediscoveryCheckIntervalTime` from 1 hour to 1 second. This was able to give me the error every run.

After checking the task ID for the failing task and the started task, there was a match in the task which was started inside the `start` method.

I'm not exactly sure why this is happening or how to resolve it. I'm not even 100% sure that this is the reason, but this is one of the leads I was able to find today.

I may need to have a chat with Brian to properly understand the intention and the data flow.

**Comment by tegefaulkes** [comment]
The error itself is happening inside the handler for the task. This is almost certainly not registering the task properly and providing a badly formatted `GestaltId` when creating the task.

The tasks created during `start` are recreating the discovery queue that was pending when the domain was last stopped. So somewhere between stopping, storing the queue and recreating it during start is butchering the `GestaltId` needed by the task.

While we're here lets double check the queue isn't acting weird. Like having duplicate nodes to discover, queue growing weirdly large. Also check how rediscovery is doing.

**Comment by aryanjassal** [comment]
> The tasks created during `start` are recreating the discovery queue that was pending when the domain was last stopped. So somewhere between stopping, storing the queue and recreating it during start is butchering the `GestaltId` needed by the task.

Actually, I checked the task data by printing it to the console, and from its creation to its execution, it remains without any parameters, so when it is called without any valid `gestaltId`s, it hits a `utils.never()`.

I have also added a print statement to the queue reconstruction loop, and it does not look like it is running either. This must mean that no tasks were pending. I have been using the prints everywhere, even places where the parameters would normally be set.

> While we're here lets double check the queue isn't acting weird. Like having duplicate nodes to discover, queue growing weirdly large.

Nope, the queue is very small, at around 0-1 active items and active promises, so I wouldn't think that this is an issue with `TaskManager`. However, given that the tasks have no parameters provided to them, both during the task creation and execution, this might signal that we are not properly storing this information.

However, other tasks like `NodeManager.syncNodeGraphHandler` rely on the parameters being set, and the logs do indicate that those parameters are properly set, so it is unlikely that the issue is being caused by `TaskManager` itself.

My guess is that the code takes some time to populate the vertex IDs for the task, and if we run the task immediately, the task would fail. This also explains why it doesn't happen in long-running sessions, only for sessions starting after a delay, as running sessions would have enough time to populate the task with proper gestalt information.

I will run this test and report with the results.

> Also check how rediscovery is doing.

It's doing pretty good 😄

**Comment by aryanjassal** [comment]
I changed the interval times from 1 second to 1 minute, so the discovery task runs later. This also did nothing, and the discovery task failed upon starting after a minute.

**Comment by aryanjassal** [comment]
I manually started the discovery process by adding a task to `start` which rediscovers all the vertices. Doing that actually completed the task successfully as the vertices had actual `gestaltId` linked with them this time, but the original task which runs at startup still failed with the same error.

Give how the method to discover vertices works when we provide the parameters using the rediscovery task, I think that we might be setting up the task incorrectly, or not updating it when we should.

**Comment by CMCDragonkai** [comment]
So the idea is that the audit domain should provide semantic observability. But we also need a diagnostic domain to provide more detailed traces.

We also want observable integration as per #444 and everything should be aligned on that with the rest of the team. I want to make sure everybody reads up on this @tegefaulkes .

**Comment by aryanjassal** [comment]
After some discussion, we realised that the path is set as `checkRediscoveryHandlerId` but the `handlerId` is set to `discoverVertexHandlerId`. The comment above the task scheduling also says `// Start up rediscovery task`, which means that the handler was probably meant to be a rediscovery task instead of a regular discovery task.

If this is the case, then the fix would be a one-liner. Otherwise, things would be a bit more complex. After I'm done with [**Polykey#311**](https://github.com/MatrixAI/Polykey-CLI/issues/311), I will work on this.

**Comment by aryanjassal** [comment]
After checking the code, there were two places where the `checkRediscoveryHandlerId` path was provided, but the `discoverVertexHandlerId` handler was being used. This was causing this error. After changing it to be correct, now the rediscovery works perfectly without the undefined behaviour warning.

I will push up a PR with this soon.

**Comment by CMCDragonkai** [comment]
That's great how can we prevent regressions of this nature in the future? Types or fast check tests?

**Comment by aryanjassal** [comment]
I don't think `fastcheck` tests would have helped us much for this issue, as it is not related to a particular input, but the entire system as a whole. To prevent this regression, a simple test checking if the relevant task was started properly and ended without errors should be sufficient.

**Comment by tegefaulkes** [comment]
This reopened itself I'm going to re-close it.

**Comment by CMCDragonkai** [comment]
> I don't think `fastcheck` tests would have helped us much for this issue, as it is not related to a particular input, but the entire system as a whole. To prevent this regression, a simple test checking if the relevant task was started properly and ended without errors should be sufficient.

Can you make sure we have a test to prevent regressions. I always think any bug fixed must have an associated test to prevent related regressions.

**Comment by aryanjassal** [comment]
I was just randomly monitoring the logs for the systemctl agent, and I got the same undefined behaviour message again. I immediately changed all the delays in the Discovery domain down from an hour to a second, but I could not replicate the issue. Even after resetting the time to the default and letting it run for about an hour, I still couldn't replicate the issue.

Here is a log of the output with enhanced output for all the run tasks.

```
✔ Please enter the password … *******************
WARN:polykey.PolykeyAgent:Moving Task v0ppqstvpo9o010ahtfvvjeth5c from Active to Queued with handler 'NodeManager.syncNodeGraphHandler'
WARN:polykey.PolykeyAgent:Moving Task v0ppqsu61n9o011bac5o238p244 from Active to Queued with handler 'Discovery.discoverVertexHandler'
(node:241169) [DEP0112] DeprecationWarning: Socket.prototype._handle is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
WARN:polykey.PolykeyAgent.NodeManager:Duplicate refreshBucket task was found for bucket 254, cancelling
WARN:polykey.PolykeyAgent.NodeManager:Duplicate refreshBucket task was found for bucket 255, cancelling
pid       	241169
nodeId    	vet1dhoduhkmn4749r8usiopivklr8i4qoh9kjnhtgeg5rie4nvh0
clientHost	::1
clientPort	42337
agentHost 	::
agentPort 	40649
WARN:polykey.PolykeyAgent.task v0ppqsu6q31o01be3mhk2lr7ih0:Task v0ppqsu6q31o01be3mhk2lr7ih0 succeeded with handler Discovery.checkForRediscoveryHandler
WARN:polykey.PolykeyAgent.NodeManager:Duplicate refreshBucket task was found for bucket 253, cancelling
WARN:polykey.PolykeyAgent.NodeManager:Duplicate refreshBucket task was found for bucket 253, cancelling
WARN:polykey.PolykeyAgent.task v0ppqsu61n9o011bac5o238p244:Task v0ppqsu61n9o011bac5o238p244 succeeded with handler Discovery.discoverVertexHandler
WARN:polykey.PolykeyAgent.task v0ppqt8n31po011cs5315dropl8:Task v0ppqt8n31po011cs5315dropl8 succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqsu7gc9o01beqauu0f1inf4:Task v0ppqsu7gc9o01beqauu0f1inf4 succeeded with handler NodeManager.refreshBucketHandler
WARN:polykey.PolykeyAgent.task v0ppqt8n3glo012tqofk6ildup8:Task v0ppqt8n3glo012tqofk6ildup8 succeeded with handler NodeManager.syncNodeGraphHandler
WARN:polykey.PolykeyAgent.task v0ppqstvpo9o010ahtfvvjeth5c:Task v0ppqstvpo9o010ahtfvvjeth5c succeeded with handler NodeManager.syncNodeGraphHandler
WARN:polykey.PolykeyAgent.task v0ppqtb9uapo013f4ba5504d6dc:Task v0ppqtb9uapo013f4ba5504d6dc succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqtb9v8to01f4hpppe6c4cig:Task v0ppqtb9v8to01f4hpppe6c4cig succeeded with handler NodeManager.refreshBucketHandler
WARN:polykey.PolykeyAgent.task v0ppqtdslf1o010i0elrgksl13c:Task v0ppqtdslf1o010i0elrgksl13c succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqtgfcu5o0146q1106o88h0c:Task v0ppqtgfcu5o0146q1106o88h0c succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqtj24ido018mcr4n8b2cc78:Task v0ppqtj24ido018mcr4n8b2cc78 succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqruobilo014h3mt6bccm8oo:Task v0ppqruobilo014h3mt6bccm8oo succeeded with handler Discovery.checkForRediscoveryHandler
WARN:polykey.PolykeyAgent.task v0ppqrvhdtdo014kfnju8nubpto:Task v0ppqrvhdtdo014kfnju8nubpto succeeded with handler Discovery.checkForRediscoveryHandler
WARN:polykey.PolykeyAgent.task v0ppqtlkrcho010n8ab69mimkfk:Task v0ppqtlkrcho010n8ab69mimkfk succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqs15qjdo01coc5oqnt0df7c:Task v0ppqs15qjdo01coc5oqnt0df7c succeeded with handler Discovery.checkForRediscoveryHandler
WARN:polykey.PolykeyAgent.task v0ppqto7i8lo01f4u2ho1gns678:Task v0ppqto7i8lo01f4u2ho1gns678 succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqtdsrado0158ouga6vmnp24:Task v0ppqtdsrado0158ouga6vmnp24 succeeded with handler NodeManager.refreshBucketHandler
WARN:polykey.PolykeyAgent.task v0ppqtqq96do010n3s9th9pq6j0:Task v0ppqtqq96do010n3s9th9pq6j0 succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqttd0ito01f2alcfndskkvk:Task v0ppqttd0ito01f2alcfndskkvk succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqtvvnp9o019nbfnjbbrvr00:Task v0ppqtvvnp9o019nbfnjbbrvr00 succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqtqqaulo01a8q72g3ps7qo4:Task v0ppqtqqaulo01a8q72g3ps7qo4 succeeded with handler NodeManager.refreshBucketHandler
^CWARN:polykey:Stopping Agent
WARN:polykey.PolykeyAgent.task v0ppqstvpbho010gcm13b4hic04:Task v0ppqstvpbho010gcm13b4hic04 succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqsu7fudo011mbpb8m6fgdbc:Task v0ppqsu7fudo011mbpb8m6fgdbc succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqstlneho01044ih2d5ln7gg:Task v0ppqstlneho01044ih2d5ln7gg succeeded with handler NodeManager.checkConnectionsHandler
WARN:polykey.PolykeyAgent.task v0ppqu2ielho017dc98tgurvnnk:Task v0ppqu2ielho017dc98tgurvnnk succeeded with handler NodeManager.checkConnectionsHandler
```

Note that the success message being a warning is only temporary. Reopening this issue as it has not been completely resolved yet.

**Comment by aryanjassal** [comment]
I observed this after I updated my Polykey agent using home manager. I had that error after a restart of the service too, which is why I was concerned. Perhaps it was re-running previously failed tasks?

I have asked Brian to run and monitor his agent for this issue, but he also has not encountered this issue. My agent is also running clean. A couple hours have gone by without this issue, but I'm keeping this open just in case anyone else also observes this issue and is able to replicate it.

**Comment by aryanjassal** [comment]
Neither me nor Brian could detect this issue happening again. My guess is that when the previous task failed, it was added to the queue anyways to be run later. After the update, it still went through the backlog, and ran the malformed task, which gave those errors. I have been running the agent continuously, and I cannot see this issue again, and I cannot replicate it either. This must mean that the issue is resolved, and the warnings observed were one-off.

I can re-open this issue if anyone else observes this issue on Polykey CLI version greater than or equal to 0.14.0.
